routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('media', 'MediaController');

Route::prefix('Customer/')->group(function (){
    Route::resource('customer', 'CustomerController');
});

Route::prefix('Audio/')->group(function (){
    Route::resource('audio', 'AudioController');
});

Route::prefix('Video/')->group(function (){
    Route::resource('video', 'VideoController');
});

Route::prefix('PDF/')->group(function (){
    Route::resource('pdf', 'PDFController');
});

Route::prefix('Written/')->group(function (){
    Route::resource('written', 'WrittenPostController');
});

resources/views/home.blade.php
@extends('layouts.main')

@section('title')
    HOME
@endsection

@section('content')
<div class="content-wrapper">

<section class="content">
      <div class="row" style="margin-left: 10px; margin-right: 10px; margin-top: 10px; margin-bottom: 0px">
          <div class="col-lg-3 col-xs-12" style="padding-bottom: 0px;">
            <!-- small box -->
            <div class="small-box bg-aqua">
              <div class="inner">
                <h3>{{$audio}}</h3>

                <p>Audio File</p>
              </div>
              <div class="icon">
                <i class="fa fa-file-audio-o"></i>
              </div>
              <a href="{{route('audio.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>

          <div class="col-lg-3 col-xs-12" style="padding-bottom: 0px;">
            <!-- small box -->
            <div class="small-box bg-green">
              <div class="inner">
                <h3>{{$video}}</h3>

                <p>Video File</p>
              </div>
              <div class="icon">
                <i class="fa fa-file-video-o"></i>
              </div>
              <a href="{{route('video.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>

          <div class="col-lg-3 col-xs-12" style="padding-bottom: 0px;">
            <!-- small box -->
            <div class="small-box bg-green">
              <div class="inner">
                <h3>{{$pdf}}</h3>

                <p>PDF</p>
              </div>
              <div class="icon">
                <i class="fa  fa-file-pdf-o"></i>
              </div>
              <a href="{{route('pdf.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>

          <div class="col-lg-3 col-xs-12" style="padding-bottom: 0px;">
            <!-- small box -->
            <div class="small-box bg-aqua">
              <div class="inner">
                <h3>{{$written}}</h3>

                <p>Handwriting</p>
              </div>
              <div class="icon">
                <i class="fa fa-hand-paper-o"></i>
              </div>
              <a href="{{route('written.index')}}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
      </div>
</section>

</div>
@endsection

resources/views/message.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{$error}}
        </div>
    @endforeach
@endif

@if(session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif