routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('media', 'MediaController');

Route::prefix('Customer/')->group(function (){
    Route::resource('customer', 'CustomerController');
});

Route::prefix('Audio/')->group(function (){
    Route::resource('audio', 'AudioController');
});

Route::prefix('Video/')->group(function (){
    Route::resource('video', 'VideoController');
});

Route::prefix('PDF/')->group(function (){
    Route::resource('pdf', 'PDFController');
});

Route::prefix('Written/')->group(function (){
    Route::resource('written', 'WrittenPostController');
});

resources/views/Written/index.blade.php
@extends('layouts.main')

@section('title')
    Customer
@endsection

@section('content')
    <div class="content-wrapper">

        <section class="content">
            <div class="row" style="margin-left: 10px; margin-right: 10px; margin-top: 10px; margin-bottom: 0px">

                <div class="col-md-2"></div>

                <div class="col-md-8">

                    @include('message')

                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">POST
                                <small>Your Story</small>
                            </h3>
                            <!-- tools box -->
                            <div class="pull-right box-tools">
                                <button type="button" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip"
                                        title="Collapse">
                                    <i class="fa fa-minus"></i></button>
                                <button type="button" class="btn btn-default btn-sm" data-widget="remove" data-toggle="tooltip"
                                        title="Remove">
                                    <i class="fa fa-times"></i></button>
                            </div>
                            <!-- /. tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body pad">
                            <form action="{{route('written.store')}}" method="post">
                                @csrf
                                <input type="text" class="form-control form-control-sm" name="post_name" placeholder="Post Name" style="margin-bottom: 5px;" required>
                                <input type="text" class="form-control form-control-sm" name="post_title" placeholder="Post Title" style="margin-bottom: 15px" required>
                                <textarea class="textarea" placeholder="Body..." name="body" required
                                style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                <input type="submit" class="btn btn-block btn-sm btn-success">
                            </form>

                            <hr>

                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>POST Name</th>
                                    <th>POST Title</th>

                                    <th></th>
                                    <th></th>
                                    <th></th>

                                </tr>
                                </thead>

                                <tbody>

                                @foreach($post_list as $value)
                                    <tr>
                                        <td>{{$value -> post_name}}</td>
                                        <td>{{$value -> post_title}}</td>

                                        <td>
                                            <a href="{{route('written.show', $value->id) }}" class="btn btn-sm btn-warning"><i class="fa fa-bars"></i></a>
                                        </td>
                                        <td>
                                            <a href="{{route('written.edit', $value->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                                        </td>
                                        <td>
                                            {!!Form::open(['action' => ['WrittenPostController@destroy', $value->id], 'method' => 'POST', 'onsubmit'=>"if(!confirm('Are You Sure want to DELETE??')){return false;}"])!!}
                                            {{Form::hidden('_method', 'DELETE')}}
                                            <button type="submit" class="btn btn-sm btn-danger" > <i class="fa fa-trash"></i></button>
                                            {!!Form::close()!!}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>
                        </div>



                    </div>


                </div>

            </div>
        </section>

    </div>
@endsection

resources/views/Written/show.blade.php
@extends('Layouts.main')

@section('title')
    Post
@endsection

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-2"></div>
                <div class="col-md-8">

                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title"> POST Show</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            POST Name: <strong> {{$post->post_name}}</strong> <br>
                            POST Title: <strong> {{$post->post_title}}</strong> <br>
                            <hr>
                            <strong>Body:</strong>{!! $post->body !!} <br>

                        </div>
                        <!-- /.box-body -->
                    </div>

                </div>

            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->

    </div>
    <!-- /.content-wrapper -->



@endsection