routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('media', 'MediaController');

Route::prefix('Customer/')->group(function (){
    Route::resource('customer', 'CustomerController');
});

Route::prefix('Audio/')->group(function (){
    Route::resource('audio', 'AudioController');
});

Route::prefix('Video/')->group(function (){
    Route::resource('video', 'VideoController');
});

Route::prefix('PDF/')->group(function (){
    Route::resource('pdf', 'PDFController');
});

Route::prefix('Written/')->group(function (){
    Route::resource('written', 'WrittenPostController');
});

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    //
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Video;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $video_list = DB::table('videos')->get();
        return view('Video/index')->with('video_list', $video_list);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->hasFile('video')){

            $file = $request->file('video');

            $filename = $request->input('video_name').'_'.time().'.'.$file->getClientOriginalExtension();
            $path = public_path().'/Video/';
            $file->move($path, $filename);

            DB::table('videos')
                ->insert([
                    'video_name' => $filename,
                    'video_type' => $file->getClientOriginalExtension(),
                    "created_at" =>  \Carbon\Carbon::now(),
                    "updated_at" => \Carbon\Carbon::now()
                ])
            ;
            $video_list = DB::table('videos')->get();
            return view('Video/index')
                ->with('video_list', $video_list)
                ->with('success', 'Video Uploaded')
                ;

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd('ops...');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('videos')->where('id', $id)->delete();
        return redirect('Video/Video')->with('success', 'Video Removed');
    }
}

resources/views/Video/index.blade.php
@extends('layouts.main')

@section('title')
    Video
@endsection

@section('content')
    <div class="content-wrapper">

        <section class="content">
            <div class="row" style="margin-left: 10px; margin-right: 10px; margin-top: 10px; margin-bottom: 0px">

                <div class="col-md-2"></div>
                <div class="col-md-8">

                    @include('message')

                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Upload Video</h3>
                        </div>

                        @include('message')
                        <!-- /.box-header -->
                        <div class="box-body">

                            {!! Form::open(['route'=>'video.store', 'method'=>'post', 'files'=>true ]) !!}
                            {{ Form::token() }}

                            <div class="form-group">
                                <div class="row">

                                    <div class="col-md-6">
                                        {!! Form::label('video_name', 'Video Name') !!}
                                    </div>
                                    <div class="col-md-6">
                                        {{ Form::text('video_name','', array('class'=>'form-control-sm', 'required')) }}
                                    </div>

                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">

                                    <div class="col-md-6">
                                        {!! Form::label('video', 'Upload Video') !!}
                                    </div>
                                    <div class="col-md-6">
                                        {{ Form::file('video', ['accept' =>  'video/mp4', 'required']) }}
                                    </div>

                                </div>
                            </div>

                            {{ Form::submit('Upload', array('class' => 'btn btn-primary btn-block btn-sm', 'style' => 'margin-top: 20px'))}}

                            {!! Form::close() !!}


                            <hr>


                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>Video Name</th>
                                    <th>Type</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>

                                </tr>
                                </thead>

                                <tbody>

                                @foreach($video_list as $value)
                                    <tr>
                                        <td>{{$value -> video_name}}</td>
                                        <td>{{$value -> video_type}}</td>

                                        <td>
                                            <a href="{{route('video.show', $value->id) }}" class="btn btn-sm btn-warning"><i class="fa fa-bars"></i></a>
                                        </td>
                                        <td>
                                            <a href="{{route('video.edit', $value->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                                        </td>
                                        <td>
                                            {!!Form::open(['action' => ['VideoController@destroy', $value->id], 'method' => 'POST', 'onsubmit'=>"if(!confirm('Are You Sure want to DELETE??')){return false;}"])!!}
                                            {{Form::hidden('_method', 'DELETE')}}
                                            <button type="submit" class="btn btn-sm btn-danger" > <i class="fa fa-trash"></i></button>
                                            {!!Form::close()!!}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>


                        </div>
                        <!-- /.box-body -->
                    </div>

                </div>

            </div>
        </section>

    </div>
@endsection

resources/views/Video/show.blade.php
@extends('Layouts.main')

@section('title')
    Customer
@endsection

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <!-- left column -->
                <div class="col-md-2"></div>
                <div class="col-md-8">

                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title"> Customer Information</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            First Name: <strong> {{$customer->first_name}}</strong> <br>
                            Last Name: <strong> {{$customer->last_name}}</strong> <br>
                            Email: <strong> {{$customer->email}}</strong><br>
                            Birthday: <strong> {{$customer->birthday}}</strong><br>
                            Gender: <strong> {{$customer->gender}}</strong><br>
                        </div>
                        <!-- /.box-body -->
                    </div>

                </div>

            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->

    </div>
    <!-- /.content-wrapper -->



@endsection